### ISSUE TITLE
acceptance: TestPartitionBank is flaky / failing

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12654]
Here:

https://teamcity.cockroachdb.com/viewLog.html?buildId=106807

https://teamcity.cockroachdb.com/viewLog.html?buildId=106820

```
=== RUN   TestPartitionBank
--- FAIL: TestPartitionBank (11.29s)
	partition.go:105: errors restoring the network: [error executing [iptables -X partition_nemesis]:
		rpc error: code = 2 desc = oci runtime error: exec failed: exit status 1
		
		]
```

**Comment by knz** [comment]
Some additional clarity:
```
[13:39:23][TestPartitionBank] 	partition.go:105: errors restoring the network: [error executing [iptables -F partition_nemesis]:
[13:39:23][TestPartitionBank] 		rpc error: code = 2 desc = oci runtime error: exec failed: exit status 1
[13:39:23][TestPartitionBank] 		
[13:39:23][TestPartitionBank] 		 error executing [iptables -X partition_nemesis]:
[13:39:23][TestPartitionBank] 		rpc error: code = 2 desc = oci runtime error: exec failed: exit status 1
[13:39:23][TestPartitionBank] 		
[13:39:23][TestPartitionBank] 		]
[13:39:23][TestPartitionBank] ##teamcity[testFailed timestamp='2017-01-04T13:39:23.599' name='TestPartitionBank' details='	partition.go:105: errors restoring the network: |[error executing |[iptables -F partition_nemesis|]:|n		rpc error: code = 2 desc = oci runtime error: exec failed: exit status 1
[13:39:23][TestPartitionBank] |n		|n		 error executing |[iptables -X partition_nemesis|]:|n		rpc error: code = 2 desc = oci runtime error: exec failed: exit status 1
[13:39:23][TestPartitionBank] |n		|n		|]']
```

Notice how the output of go-test-teamcity is clobbered.

May be caused by #12671 ?

**Comment by knz** [comment]
@jordanlewis can you have a look at the output in the previous comment, and see what made go-test-teamcity spoil its marker?

**Comment by knz** [comment]
Bisected; the regression was introduced
7661e2c9cdabad545573b4e76f76256185c916a5

@andreimatei it's all yours.

**Comment by knz** [comment]
This test is now (temporarily) skipped (#12662 - dc42004ef47ab865832b6002c61ce97e763e981b)

**Comment by tschottdorf** [comment]
This code has been deleted.
