### PR TITLE
sql: remove some old aliases

### PR DESCRIPTION
**Pull request by ajwerner**
Picking up the scraps of the some of the rename work.

Release note: None

### CODE REVIEW

**Review by rohany — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r=rohany

**Comment by otan** [comment]
```

[16:29:45][Ensure generated code is up-to-date] pkg/sql/alter_schema.go:56:25: undefined: MutableSchemaDescriptor
[16:29:45][Ensure generated code is up-to-date] pkg/sql/drop_schema.go:104:24: undefined: MutableSchemaDescriptor
```

i think it's this

bors r-

**Comment by ajwerner** [comment]
Updated, merge skew :(

**Comment by otan** [comment]
image

at least it didn't brick master :) !
