### ISSUE TITLE
bazel: dev bench build fails when `_test` target isn't specified

### ISSUE THREAD

**Issue by shubhamdhama** [cockroachdb/cockroach#147833]
Let's take the example of `pkg/rpc`: `./dev bench ./pkg/rpc/` is failing with:

```bash
./dev bench ./pkg/rpc/
$ bazel test pkg/rpc:all --nocache_test_results --test_arg -test.run=- --test_arg -test.bench=. --test_sharding_strategy=disabled --test_arg -test.cpu --test_arg 1 --test_arg -test.benchmem --crdb_test_off --test_env COCKROACH_TEST_FIXTURES_DIR=/Users/shubham/Library/Caches/crdb-test-fixtures --sandbox_writable_path=/Users/shubham/Library/Caches/crdb-test-fixtures --test_output streamed
ERROR: /Users/shubham/go/src/github.com/cockroachdb/cockroach/pkg/rpc/BUILD.bazel:194:17: GoCompilePkg pkg/rpc/rpc_go_proto.a failed: (Exit 1): builder failed: error executing GoCompilePkg command (from target //pkg/rpc:rpc_go_proto) bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -goroot bazel-out/darwin_arm64-fastbuild/bin/external/io_bazel_rules_go/stdlib_ ... (remaining 54 arguments skipped)
...
compilepkg: missing strict dependencies:
        /private/var/tmp/_bazel_shubham/4d3549f97f2aa10f55257345e0d878f1/sandbox/darwin-sandbox/7383/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/rpc/rpc_go_proto_/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go: import of "github.com/cockroachdb/cockroach/pkg/util/uuid"
...
```

But `./dev bench pkg/rpc:rpc_test` works.

This happens because `bazel test pkg/rpc:all` also includes the `rpc_go_proto` target in the build. If we do `dev build pkg/rpc:rpc_go_proto`, it would fail, which explains why the above `dev bench` is failing. This also explains why `dev bench pkg/rpc:rpc_test` would work (the target is specified).

This bug was introduced in b3849a87212. The problem occurs when `//pkg/cmd/protoc-gen-go-drpc:protoc-gen-go-drpc_compiler` is included in `go_proto_library`.

https://github.com/cockroachdb/cockroach/blob/fb15a49058e015e1fc104e8884292c734975ccd6/pkg/rpc/BUILD.bazel#L194-L207

Even if we include `//pkg/util/uuid` manually, it still creates a problem, like this:

```
bazel-out/darwin_arm64-fastbuild/bin/pkg/rpc/rpc_go_proto_/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:210:37: cannot use m (variable of type *RemoteOffset) as "github.com/gogo/protobuf/proto".Message value in argument to xxx_messageInfo_RemoteOffset.Merge: *RemoteOffset does not implement "github.com/gogo/protobuf/proto".Message (missing method String)
bazel-out/darwin_arm64-fastbuild/bin/pkg/rpc/rpc_go_proto_/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:216:46: cannot use m (variable of type *RemoteOffset) as "github.com/gogo/protobuf/proto".Message value in argument to xxx_messageInfo_RemoteOffset.DiscardUnknown: *RemoteOffset does not implement "github.com/gogo/protobuf/proto".Message (missing method String)
```

Here, `heartbeat.proto` uses `option (gogoproto.goproto_stringer) = false` for `RemoteOffset`, which results in it not generating its `String()` method. This then fails when it's checked against the required interface. This method is actually defined in `heartbeat.go`, a checked-in file, not a generated file. The question is why it works when the DRPC compiler is not specified; that is, why mentioning two compilers creates this mess.

It appears none of the dependencies are available in the final step of this compiler code generation.

We have two options here:
1. Like `dev test`, even if the target isn't specified, use the `_test` target.
2. Fix `dev build pkg/rpc:rpc_go_proto`.

As of now it appears the scope of this issue is only `dev bench` when the `_test` target isn't specified.

@rickystewart / @cockroachdb/dev-inf , I'd appreciate any ideas you might have here.

cc: @stevendanna  for reporting this problem.

Jira issue: CRDB-51275

**Comment by rickystewart** [comment]
That issue is #161218.
