### PR TITLE
deps: bump cgosymbolizer

### LINKED ISSUE #55356: vendor: consider bumping github.com/ianlancetaylor/cgosymbolizer version to latest to allow building on s390x
Hello,

I am wondering if `github.com/ianlancetaylor/cgosymbolizer` in the vendor folder can be updated to its latest version? I originally thought the update would be simply raising a PR to `cockroach/vendor` repository to include the fix. However, through some searching, it seems like it is not the case and instead you need to bump the version of that repo to be latest? 

To provide a bit more information on the failure, building CockroachDB on s390x will currently have the following failure:
```
# github.com/ianlancetaylor/cgosymbolizer                        
In file included from dwarf.c:33:0:                            
config.h:9:2: error: #error BACKTRACE_ELF_SIZE unknown                
 #error BACKTRACE_ELF_SIZE unknown                                                         
  ^~~~~          
``` 

The fix for this failure is included in https://github.com/ianlancetaylor/cgosymbolizer/pull/9, so bumping the version fixes the error seen on s390x. This could help the cross compiling effort on s390x as well, see the binary section in https://github.com/cockroachdb/cockroach/issues/55307. 

Thanks.

### PR DESCRIPTION
**Pull request by knz**
Fixes #55356 

Required for #55307 

This is needed to pick up the latest Cgo changes, including support
for the new target platforms of the Go compiler.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM though I have no ability to properly review those upstream changes.

**Comment by knz** [comment]
thanks

bors r=petermattis
