### PR TITLE
make: fix kerberos build on gcc10

### LINKED ISSUE #49734: build: krb-related errors
Hi developers, When i trying build cockroachdb from source, it will fail when build krb.

**To Reproduce**
Follow the instruction in https://wiki.crdb.io/wiki/spaces/CRDB/pages/181338446/Getting+and+building+from+source, trying to build cockroachdb, but it fail when linking kdb5_util

1.mkdir -p $(go env GOPATH)/src/github.com/cockroachdb
2.cd $(go env GOPATH)/src/github.com/cockroachdb
3.git clone https://github.com/cockroachdb/cockroach
4.cd cockroach
5.make buildshort

**Expected behavior**
Build success

**Additional data / screenshots**
Here is part of the build output

making all in kadmin/dbutil...
gcc -L../../lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/usr/local/lib -g -O2   -o kdb5_util kdb5_util.o kdb5_create.o kadm5_create.o kdb5_destroy.o kdb5_stash.o import_err.o strtok.o dump.o ovload.o kdb5_mkey.o tabdump.o tdumputil.o ../cli/getdate.o -lkadm5srv_mit  -lkdb5 -lkrb5_db2 -lkadm5srv_mit -lgssrpc -lgssapi_krb5 -lgssrpc -lgssapi_krb5 -ldl -pthread  -lkrb5 -lk5crypto -lcom_err -lkrb5support  -lkeyutils -lresolv  -ldl
/usr/bin/ld: ../../lib/libkadm5srv_mit.a(server_kdb.o):/home/rebellion/go/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/lib/kadm5/srv/server_kdb.c:18: multiple definition of `master_keyblock'; kdb5_util.o:(.bss+0x40): first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:663: kdb5_util] Error 1
make[2]: *** [Makefile:853: all-recurse] Error 1
make[1]: *** [Makefile:1533: all-recurse] Error 1
make: *** [Makefile:776: /home/rebellion/go/native/x86_64-pc-linux-gnu/krb5/lib/libgssapi_krb5.a] Error 2
make: *** Deleting file '/home/rebellion/go/native/x86_64-pc-linux-gnu/krb5/lib/libgssapi_krb5.a'

**Environment:**
 - CockroachDB version 20.1.1, master branch, commit id 021d87644837dfc7e7cd56af386f94b93f41623e
 - Server OS: Arch Linux version 5.6.14-arch1-1 (linux@archlinux) (gcc version 10.1.0 (GCC))
 - Client app: None

**Additional context**

### PR DESCRIPTION
**Pull request by andreimatei**
gcc-10 switched the default to -fno-common, which makes kerberos fail to
build with --enable-static because of duplicate definitions.

Fixes #49734

Release note (build change): CRDB now builds on Ubuntu 20.10 and other
distos using gcc-10.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58895#-:-MQvzyUhDXeD7RKKP486:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58895#-:-MQwPhWyElP-kXV_PHg9:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained
