### ISSUE TITLE
build: upgrade to go 1.12

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#35197]
NOTE: We are not planning on upgrading for the 19.1 release.

Known issues:
- [x] (#35195) cgo compilation error due to missing C.bool type casts.
- [ ] go vet `-shadow` option no longer supported. See the [release notes](https://golang.org/doc/go1.12#vet) for details on a fix.
- [x] (#17770) use `runtime.CallersFrames` instead of `runtime.Callers`.
- [x] (#35636, #35645) test failuers in sqlbase

**Comment by bdarnell** [comment]
Even though 19.2 will be the first CockroachDB release to officially build with Go 1.12, we should probably backport the changes here to our supported release branches (at least 2.1 and 19.1) for developer convenience (so that people who have upgraded to newer go versions don't have to maintain a separate toolchain or work entirely in docker).

**Comment by knz** [comment]
Folded into #35637.
