### ISSUE TITLE
Source code can't compile on CentOS 7.3 x64 , failed on step "go install" 

### ISSUE THREAD

**Issue by GangLiCN** [cockroachdb/cockroach#35725]
**Describe the problem**

Cockroach source code(version: 2.1.6) compile failed on step "go install"

**To Reproduce**
1) Download Cockroach source code from  below url:
https://binaries.cockroachdb.com/cockroach-v2.1.6.src.tgz 

2) Extract the package and execute "make build", it failed, there are too many errors from the output,  The first error comes from the output of "go install":

runtime/internal/sys
internal/cpu
runtime/internal/atomic

runtime/internal/sys
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:8:24: ArchFamily redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:8:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:8:24: undefined: WASM
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:9:24: BigEndian redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:9:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:10:24: CacheLineSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:10:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:11:24: DefaultPhysPageSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:11:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:12:24: PCQuantum redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:12:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:13:24: Int64Align redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:13:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:14:24: HugePageSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:14:29
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:15:24: MinFrameSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:15:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:18:6: Uintreg redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:18:6
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:8:24: too many errors

**Additional data / screenshots**

**Environment:**
 - CockroachDB version: 2.1.6
 - Server OS: CentOS 7.3 x86-64
 - Go version:  1.10.8 (also tried 1.11 and 1.12, both failed)
 
My Questions are:
1) Which version of "Go" had been tested OK for Cockroach source code compile ?
2) For some other dependent library or files, e.g. GCC,  which version of GCC had been tested
successfully for source code compile ?   from README file, it just says "GCC prior to 6.0 does not work due to this issue.", this statement is unclear and seems helpless to user.

**Comment by GangLiCN** [comment]
The issue had been fixed .

It looks like the "Go" binary packages downloaded from  golang.google.cn  can't work,  I downloaded
source code of Go and compiled it, all errors went way.

**Comment by knz** [comment]
Excellent! very good news. Thank you for the update.
