### PR TITLE
upgrades: remove upgrade granting CREATELOGIN role opt

### LINKED ISSUE #92230: roachtest: tpcc/mixed-headroom/multiple-upgrades/n5cpu16 failed
roachtest.tpcc/mixed-headroom/multiple-upgrades/n5cpu16 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7605127?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7605127?buildTab=artifacts#/tpcc/mixed-headroom/multiple-upgrades/n5cpu16) on master @ [cfb5ae9a96e1770daa4aef1615a46e212b561a84](https://github.com/cockroachdb/cockroach/commits/cfb5ae9a96e1770daa4aef1615a46e212b561a84):

```
test artifacts and logs in: /artifacts/tpcc/mixed-headroom/multiple-upgrades/n5cpu16/run_1
(test_impl.go:291).Fatal: 2: expected version 1000022.2-8, got 1000022.1-16
(test_impl.go:291).Fatal: monitor failure: monitor task failed: output in run_170102.906212042_n5_cockroach_workload_run_tpcc: ./cockroach workload run tpcc --warehouses=909 --histograms=perf/stats.json  --ramp=5m0s --duration=1h40m0s --prometheus-port=2112 --pprofport=33333  {pgurl:1-4} returned: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=true</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/mixed-headroom/multiple-upgrades/n5cpu16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21665

### LINKED ISSUE #92371: roachtest: cdc/mixed-versions failed
roachtest.cdc/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7655667?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7655667?buildTab=artifacts#/cdc/mixed-versions) on master @ [0d9669a8669cf5abe22b61e1f1faf9a520f2f372](https://github.com/cockroachdb/cockroach/commits/0d9669a8669cf5abe22b61e1f1faf9a520f2f372):

```
test artifacts and logs in: /artifacts/cdc/mixed-versions/run_1
(test_impl.go:314).Errorf: test timed out (30m0s)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21725

### LINKED ISSUE #92569: upgrade: `add CREATELOGIN where a role already has CREATEROLE` permanent upgrade fails
**Describe the problem**

The `add CREATELOGIN where a role already has CREATEROLE` permanent upgrade, introduced in #91627, fails with the following error message:

```
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156  job 817723912734932995: running execution encountered retriable error: non-cancelable: running migration for 0.0-2: ‹add CREATELOGIN where a role already has CREATEROLE›: null value in column ‹"user_id"› violates not-null constraint
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +(1) attached stack trace
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  -- stack trace:
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1328
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:412
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:332
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +Wraps: (2) non-cancelable
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +Wraps: (3) attached stack trace
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  -- stack trace:
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/upgrade/upgradejob.resumer.Resume
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/upgrade/upgradejob/upgrade_job.go:131
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1297
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1298
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:412
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:332
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
I221128 07:25:01.923960 22486 jobs/registry.go:1330 ⋮ [n1] 156 +  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
```

This is causing a few mixed-version roachtests to time out: #92230, #92371.

Jira issue: CRDB-21872

### PR DESCRIPTION
**Pull request by andreimatei**
This patch removes a permanent upgrade that was granting the CREATELOGIN role option to users that had the CREATEROLE option. This upgrade was introduced in 20.2, meant to grant the then-new CREATELOGIN option to users created in 20.1 and prior that had the CREATEROLE option (CREATELOGIN was being split from CREATEROLE).

This code stayed around as a startupmigration since it was introduced, even though it didn't make sense for it to stay around after 20.2. Technically, I think this startup migration should have had the flag `IncludedInBootstrap=v20.2`, since we don't want it to run for clusters created at or after 20.2; this migration is not idempotent in the general sense, since it potentially picks up new, unintended users when it runs. Since 22.2, this migration would fail to run on anything but an empty system.role_options table because it would attempt to put NULLs into a non-nullable column. This was all benign since the startupmigrations had protection in place, preventing them for running a 2nd time after a completed attempt. So, for upgraded cluster, the migration only when the first 20.2 node came up, and for new clusters it would be a no-op since the system.role_options table starts empty.

This migration became problematic in #91627 when I've turned the startupmigrations into upgrades. These upgrades run once when upgrading to 23.1; I'm relying on their idempotence.

Fixes #92230
Fixes #92371
Fixes #92569

Release note: None
Epic: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
good; thanks!
