### ISSUE TITLE
build fails on FreeBSD due to borked upgrade to newer gosigar

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#33198]
**Describe the problem**

`make build` fails on FreeBSD 12

```
# github.com/cockroachdb/cockroach/vendor/github.com/elastic/gosigar
vendor/github.com/elastic/gosigar/sigar_freebsd.go:101:27: undefined: runtime
```

Regression since #32984

cc @RaduBerinde 

(I'll have a look)

**Comment by knz** [comment]
`import "runtime"` at the top fixes it. I wonder why the upstream package didn't notice.

**Comment by knz** [comment]
Fixed by  #34244.
