### ISSUE TITLE
vendor: consider bumping github.com/ianlancetaylor/cgosymbolizer version to latest to allow building on s390x

### ISSUE THREAD

**Issue by ruixin-bao** [cockroachdb/cockroach#55356]
Hello,

I am wondering if `github.com/ianlancetaylor/cgosymbolizer` in the vendor folder can be updated to its latest version? I originally thought the update would be simply raising a PR to `cockroach/vendor` repository to include the fix. However, through some searching, it seems like it is not the case and instead you need to bump the version of that repo to be latest? 

To provide a bit more information on the failure, building CockroachDB on s390x will currently have the following failure:
```
# github.com/ianlancetaylor/cgosymbolizer                        
In file included from dwarf.c:33:0:                            
config.h:9:2: error: #error BACKTRACE_ELF_SIZE unknown                
 #error BACKTRACE_ELF_SIZE unknown                                                         
  ^~~~~          
``` 

The fix for this failure is included in https://github.com/ianlancetaylor/cgosymbolizer/pull/9, so bumping the version fixes the error seen on s390x. This could help the cross compiling effort on s390x as well, see the binary section in https://github.com/cockroachdb/cockroach/issues/55307. 

Thanks.

**Comment by knz** [comment]
@ruixin-bao what is your question exactly? Do you want to learn how to bump a dependency, or are you expecting someone in the crdb team to do this?

**Comment by ruixin-bao** [comment]
@knz Thanks for the swift reply! 

> what is your question exactly? Do you want to learn how to bump a dependency, or are you expecting someone in the crdb team to do this?

I think the latter if you don't mind and if there is any testing / help I can provide, let me know. I would like to raise a PR myself but I still need to wait a while for legal clearance to do so. I have followed the steps listed at https://github.com/cockroachdb/cockroach/tree/master/build#installing-or-updating-a-dependency and run local test on an intel machine. It looks like bumping the version does not affect the test results (all test passing with `make test`).

Best,
Ruixin (Peter)

**Comment by ruixin-bao** [comment]
@knz, thank you for raising the PR, much appreciated.
