### PR TITLE
importer: track entry counts in distributed merge import path

### LINKED ISSUE #163380: sql/importer: TestImportDistributedMergeStoragePrefixTracking failed
sql/importer.TestImportDistributedMergeStoragePrefixTracking [failed](https://mesolite.cluster.engflow.com/invocations/default/d5143ff1-ff32-478b-9889-bfa772c96cbd?testReportRun=1&testReportShard=2&testReportAttempt=1#targets-Ly9wa2cvc3FsL2ltcG9ydGVyOmltcG9ydGVyX3Rlc3Q=) on master @ [ff713391ac6a0dd5d44fe68888afab012955c8b5](https://github.com/cockroachdb/cockroach/commits/ff713391ac6a0dd5d44fe68888afab012955c8b5):

```
=== RUN   TestImportDistributedMergeStoragePrefixTracking
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestImportDistributedMergeStoragePrefixTracking2893526272
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:679: DRPC is enabled (via override by TestingGlobalDRPCOption)
    import_stmt_test.go:5774: error executing query="IMPORT INTO t (k, v) CSV DATA ('nodelocal://1/data.csv')" args=[]: pq: failed to wait for inspect job 1149424083727679489 for table t: INSPECT found inconsistencies
        HINT: Run 'SHOW INSPECT ERRORS FOR JOB 1149424083727679489 WITH DETAILS' for more information.
    panic.go:615: -- test log scope end --
test logs left over in: outputs.zip/logTestImportDistributedMergeStoragePrefixTracking2893526272
--- FAIL: TestImportDistributedMergeStoragePrefixTracking (3.22s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=2</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestImportDistributedMergeStoragePrefixTracking.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60190

### LINKED ISSUE #163425: sql/importer: TestImportDistributedMerge failed
sql/importer.TestImportDistributedMerge [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21099341?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21099341?buildTab=artifacts#/) on master @ [36acd5e7dfba079c4f01baf52cbeeecd2e21538c](https://github.com/cockroachdb/cockroach/commits/36acd5e7dfba079c4f01baf52cbeeecd2e21538c):

```
=== RUN   TestImportDistributedMerge
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/70a5a808e3ce2b7281988192b5855abf/logTestImportDistributedMerge960231792
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:183: automatically injected an external process virtual cluster under test; see comment at top of test_server_shim.go for details.
    test_server_shim.go:679: DRPC is enabled (via override by TestingGlobalDRPCOption)
I260212 14:45:37.454180 1 (gostd) rand.go:288  [-] 1  random seed: -807741586418065077
    import_stmt_test.go:131: error executing query="IMPORT INTO customers (id, name, email) CSV DATA ($1)" args=["nodelocal://1/data.csv"]: pq: failed to wait for inspect job 1149623139853238273 for table customers: INSPECT found inconsistencies
        HINT: Run 'SHOW INSPECT ERRORS FOR JOB 1149623139853238273 WITH DETAILS' for more information.
    panic.go:615: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/70a5a808e3ce2b7281988192b5855abf/logTestImportDistributedMerge960231792
--- FAIL: TestImportDistributedMerge (32.92s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestImportDistributedMerge.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60217

### PR DESCRIPTION
**Pull request by rafiss**
The distributed merge import path uses `mergeImportBulkAdder` which embeds `bulksst.Writer`. Unlike the KV-based `SSTBatcher` used in the legacy path, `Writer.GetSummary()` returns an empty `EntryCounts` map. This caused the INSPECT row count validation (introduced in PR #161289) to compare an expected count of 0 against the actual row count, always finding a mismatch when the metamorphic `import-row-count-validation` constant selected `sync` mode.

Fix this by overriding `SetIndexID`, `Add`, and `GetSummary` on `mergeImportBulkAdder` to track entry counts per
`BulkOpSummaryID(tableID, indexID)`, matching what the legacy path already provides via `SSTBatcher`.

Resolves: #163425
Resolves: #163380

Release note: None

### CODE REVIEW

**Review by spilchen — APPROVED** [review]
:lgtm: I had a suggestion for a minor perf improvement

> @spilchen reviewed 2 files and all commit messages, and made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/163462#-:-OlMFhFk3nJCqEvuo86z:b-xey3oe)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mw5h and @rafiss).

___
*[`pkg/sql/importer/import_processor.go` line 817 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/163462#-OlMFPSx8eMxLTxynyk-:-OlMFPSx8eMxLTxynyk0:b56qiv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1478fab87c76bea54ba4f1103149df1510432f5/pkg/sql/importer/import_processor.go#L817)):*
> ```Go
> 		return err
> 	}
> 	summaryID := kvpb.BulkOpSummaryID(miba.tableID, uint64(miba.currentIndexID))
> ```

nit: I'm guessing that `Add()` is the hot path here. We may want to compute the summaryID when `SetIndexID()` called as a perf improvement.

**Review by rafiss — COMMENTED** [review]
/trunk merge

TFTR!

> @rafiss made 2 comments and resolved 1 discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/163462#-:-OlMPdT5EGswhoG9d0MB:b4lcgvj)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mw5h and @spilchen).

___
*[`pkg/sql/importer/import_processor.go` line 817 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/163462#-OlMFPSx8eMxLTxynyk-:-OlMPcgLAek5fQrQkof0:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1478fab87c76bea54ba4f1103149df1510432f5/pkg/sql/importer/import_processor.go#L817)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: I'm guessing that `Add()` is the hot path here. We may want to compute the summaryID when `SetIndexID()` called as a perf improvement.
</blockquote></details>

done
