### ISSUE TITLE
Cockroach fails to build on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by fxcoudert** [cockroachdb/cockroach#30765]
**BUG REPORT**

- Which version of CockroachDB are you using?

Trying to compile 2.0.5

- What did you do?

`make install`

- What did you expect to see?

Successful compilation.

- What did you see instead?

```
# github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix
Undefined symbols for architecture x86_64:
  "_fn_complete", referenced from:
      __el_rl_complete in _x003.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

which is likely due to https://github.com/knz/go-libedit/pull/12

- What was the impact?

We cannot distribute cockroach in Homebrew :( https://github.com/Homebrew/homebrew-core/issues/32465

**Comment by knz** [comment]
Fixed in  https://github.com/knz/go-libedit/pull/13 

will bump dep in cockroachdb

**Comment by orefalo** [comment]
same issue

**Comment by benesch** [comment]
Hi Olvier,

Sorry about this. It’ll be fixed in v2.1.0-rc.1, which is slated for
release this upcoming Monday. We’ll release a v2.0.7 with the fix within a
few weeks as well.

In the meantime, if you can tolerate the latest development version, it’s
possible to build from source. `brew install cockroach --HEAD` will do this
heavy lifting for you, or you can follow the instructions in
CONTRIBUTING.md.

**Comment by orefalo** [comment]
Thank you for quick feedback.
