### ISSUE TITLE
build: pre-built c-deps archives cause build failures on linux

### ISSUE THREAD

**Issue by dk-lockdown** [cockroachdb/cockroach#110799]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

refer to: [80389](https://github.com/cockroachdb/cockroach/issues/80389)

Building on Linux after https://github.com/cockroachdb/cockroach/commit/6cbd07ee6fbfb92706e8cdc8c559960b1bc41663 fails with the following
```
$ ./dev generate
ERROR: /home/scott/dksl/git/cockroach/pkg/ccl/gssapiccl/BUILD.bazel:4:11: GoCompilePkg pkg/ccl/gssapiccl/gssapiccl.a [for tool] failed: (Exit 1): builder failed: error executing command (from target //pkg/ccl/gssapiccl:gssapiccl) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags bazel,gss,bazel,gss -src pkg/ccl/gssapiccl/get_user.go -src ... (remaining 53 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/usr/bin/ld.gold: error: cannot find -lresolv_wrapper
/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-dbg/bin/c-deps/libkrb5_foreign.build_tmpdir/src/lib/krb5/os/dnsglue.c:156: error: undefined reference to '__res_nsearch'
collect2: error: ld returned 1 exit status
compilepkg: error running subcommand /usr/bin/gcc: exit status 1
Target //pkg/gen:gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 689.980s, Critical Path: 393.33s
INFO: 1782 processes: 21 internal, 1761 linux-sandbox.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
ERROR: generating target //pkg/gen: exit status 1
```

**Expected behavior**

Building on Linux should succeed.

**Environment:**
```
$ uname -a
Linux scott-virtual-machine 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Additional context**
What was the impact?

Jira issue: CRDB-31628

**Comment by rickystewart** [comment]
Hey @dk-lockdown: sorry, the pre-built c-deps are a little messy and things don't cleanly work on Ubuntu 22.04 yet. You have a couple options:

1. (Lowest friction) Just remove the string `-lresolv_wrapper` from `pkg/ccl/gssapiccl/BUILD.bazel`. The package no longer exists in Ubuntu 22.04 (only on 20.04 and prior) and to my knowledge is just unnecessary, so you can just delete that. I would expect the build to complete cleanly once you do so.
2. Use a cross-toolchain. In your `.bazelrc.user`, use `build --config=crosslinux` (or `--config=crosslinuxarm` for an ARM machine) instead of `build --config=dev`. In general, this is preferable since you won't encounter dependency errors like this -- the cross-toolchains have all dependencies installed already and are guaranteed to work since we use them in CI. However some people prefer to use their own system toolchain for whatever reason.

**Comment by dk-lockdown** [comment]
@rickystewart Problem solved, thanks a lot!
