### PR TITLE
build:  install netbase in builder

### LINKED ISSUE #28504: build: update the builder image to include netbase
Found while working on #28502: the builder image misses /etc/services.

### PR DESCRIPTION
**Pull request by knz**
Fixes #28504.

The builder needs /etc/services for some tests. Install `netbase` to
provide it.

### CODE REVIEW

**Comment by knz** [comment]
(not ready yet; I haven't yet been able to complete the image build)

**Comment by benesch** [comment]
I know @bdarnell had some concerns about bumping the builder image’s OS. I’m on board with it though.

**Comment by bdarnell** [comment]
I have concerns about bumping the OS used by roachprod (different time synchronization daemons are installed by default, which will break some roachtests). Updating the builder is fine with me.

**Comment by knz** [comment]
Got bad news: the GCC provided by our crosstools setup doesn't build with the newest gcc from ubuntu 18.04:

```
[ERROR]    /build/.build/src/gcc-6.3.0/gcc/ubsan.c:1474:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
```

We need to bump things here, but I don't know how.

**Comment by knz** [comment]
Completed without distro bump. PTAL

**Comment by knz** [comment]
unfortunately I see their latest release is 1.23.0 (from a year ago) and there hasn't been a release since then with the fix. What's their release schedule?

bors r+

**Comment by benesch** [comment]
Typical of an underfunded open source project that's maintained in someone's limited free time, I'm afraid: https://github.com/crosstool-ng/crosstool-ng/issues/889#issuecomment-360546170

**Comment by bdarnell** [comment]
It's too bad that debian doesn't automatically sync `/etc/services` with IANA. Our port 26257 still isn't there.

**Comment by knz** [comment]
eventually we'll get there.

Maybe it's just a question of preparing the update ourselves and ping the upstream maintainer.

**Comment by benesch** [comment]
Debian doesn't typically list a port in /etc/services unless the software
that uses that port is also part of the Debian package repositories. e.g.
see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799047.
