### PR TITLE
roachtest: add roachtest against pg ruby driver

### LINKED ISSUE #62472: roachtest: Add pg (Ruby) driver test suite to CI nightlies
Ruby and Javascript are both prioritized languages for CockroachDB. We support a variety of tools that underneath rely on the Postgres drivers. We should add test suites for pg (Ruby) and pg (Node.js) to our nightly test and triage failures similar to what we do with Go, Java, and Python driver test suites.

### PR DESCRIPTION
**Pull request by RichardJCai**
roachtest: add roachtest against pg ruby driver

Release note: None

Resolves #62472

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[BUILD.bazel, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjtrYz-79oNqtYW_ae:-MYjtrYz-79oNqtYW_af:bbnbc79) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/BUILD.bazel#L202)):*
> ```Starlark
> go_library(
>     name = "cockroach_lib",
>     srcs = ["get_tests.go"],
> ```

what is this doing? i don't see why the new test needs these changes
___
*[pkg/cmd/roachtest/ruby_pg.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjuAP_BQMwGtapvQpb:-MYjuAP_BQMwGtapvQpc:bxz8joj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L24)):*
> ```Go
> 
> var rubyPGTestFailureRegex = regexp.MustCompile(`^rspec ./.*# .*`)
> var supportedRailsVersionRubyPG = "6.1"
> ```

do we actually need Ruby on Rails to test here? I would expect it to not be needed, since Rails is an ORM that sits above the driver
___
*[pkg/cmd/roachtest/ruby_pg.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjuUhCCfAl72r6M9QN:-MYjuUhCCfAl72r6M9QO:bcwpeyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L126)):*
> ```Go
> 			fmt.Sprintf(
> 				`cd /mnt/data1/ruby-pg/ && `+
> 					`RAILS_VERSION=%s sudo bundle install`, supportedRailsVersionRubyPG),
> ```

i wouldn't expect that  we need to set the rails version here
___
*[pkg/cmd/roachtest/ruby_pg.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjuirL3krXxRhUww9l:-MYjuirL3krXxRhUww9m:b7hz9do) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L140)):*
> ```Go
> 		if err := repeatRunE(
> 			ctx, c, node, "configuring tests to use cockroach",
> 			"curl https://gist.githubusercontent.com/RichardJCai/60fa14ca95f19595e9974946cea99c07/raw/f4dc86a8c44eca4a9814e8ff793e862d3068f386/gistfile1.txt  --output /mnt/data1/ruby-pg/spec/helpers.rb",
> ```

it feels like it would be better if we could just have this config file in the code here too -- for example see how we do the django config in django.go. since this one is more code, you could make a separate file that just has one const string

this way if we need to modify it in the future, it will be easier
___
*[pkg/cmd/roachtest/ruby_pg.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjuuQR38b1TNzDQbSs:-MYjuuQSCS9drzwwNVqS:b-7ne4oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L145)):*
> ```Go
> 		}
> 
> 		//_ = c.RunE(ctx, node, `cd /mnt/data1/ruby-pg/ && sudo rake`)
> ```

commented code
___
*[pkg/cmd/roachtest/ruby_pg.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjwiHZ2D8eX6V4oR6P:-MYjwiHZ2D8eX6V4oR6Q:bs4xfia) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L165)):*
> ```Go
> 
> 		scanner := bufio.NewScanner(bytes.NewReader(rawResults))
> 		for scanner.Scan() {
> ```

consider adding a function like `(r *ormTestsResults) parseRubyUnitTestOutput` .. hmm though maybe not needed since we won't have any other ruby tests
___
*[pkg/cmd/roachtest/ruby_pg.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjvPpPCpz2QsACObPS:-MYjvPpPCpz2QsACObPT:b710yq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L171)):*
> ```Go
> 			}
> 			if len(match) != 1 {
> 				log.Warningf(ctx, "expected one match for test name, found: %d", len(match))
> ```

i think we should fail more loudly if this happens -- fail the test rather than warning
___
*[pkg/cmd/roachtest/ruby_pg.go, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjvZ9QEIaB2Bf4jK9s:-MYjvZ9QEIaB2Bf4jK9t:b-h8u6ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L185)):*
> ```Go
> 			strs := regexp.MustCompile("^rspec .*.rb.*([0-9]|]) # ").Split(test, -1)
> 			if len(strs) != 2 {
> 				log.Warningf(ctx, "length not 2")
> ```

this could also error
___
*[pkg/cmd/roachtest/ruby_pg_blocklist.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjwqoF3pNO_yoyKZmr:-MYjwqoF3pNO_yoyKZms:b-4klph) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg_blocklist.go#L20)):*
> ```Go
> 
> var rubyPGBlockList21_1 = blocklist{
> 	"PG::TypeMapByColumn will deny copy queries with different column count":                                                                                                                                                    "63642",
> ```

as we talked about, i'll do an initial pass to get down to root causes at least for some of the tests. the others ones should just be "unknown"

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[BUILD.bazel, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjtrYz-79oNqtYW_ae:-MZEWe6P9g5EUXBcpfnQ:b-rfxbwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/BUILD.bazel#L202)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what is this doing? i don't see why the new test needs these changes
</blockquote></details>

Removed, idk why `make bazel-generate` changed this.
___
*[pkg/cmd/roachtest/ruby_pg.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjuAP_BQMwGtapvQpb:-MZEWiVyA4wu_98y78AY:b-5mekdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L24)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we actually need Ruby on Rails to test here? I would expect it to not be needed, since Rails is an ORM that sits above the driver
</blockquote></details>

Nope removed
___
*[pkg/cmd/roachtest/ruby_pg.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjuUhCCfAl72r6M9QN:-MZEWjnQ3W9U4YNq0j71:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L126)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i wouldn't expect that  we need to set the rails version here
</blockquote></details>

Removed
___
*[pkg/cmd/roachtest/ruby_pg.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjuirL3krXxRhUww9l:-MZEWkap98LDlLi_NWIn:bh0rfzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L140)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it feels like it would be better if we could just have this config file in the code here too -- for example see how we do the django config in django.go. since this one is more code, you could make a separate file that just has one const string

this way if we need to modify it in the future, it will be easier
</blockquote></details>

For some reason, `echo ...` runs into a formatting error. Updated to just include the file and use Put
___
*[pkg/cmd/roachtest/ruby_pg.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjuuQR38b1TNzDQbSs:-MZEWvqV3bNg5SkS84IC:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L145)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

commented code
</blockquote></details>

Removed
___
*[pkg/cmd/roachtest/ruby_pg.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjwiHZ2D8eX6V4oR6P:-MZEWyMW5vnvjQpteY5i:bfs0eng) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L165)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

consider adding a function like `(r *ormTestsResults) parseRubyUnitTestOutput` .. hmm though maybe not needed since we won't have any other ruby tests
</blockquote></details>

Not entirely sure this is extensible for other ruby tests either, not sure if the test output is consistent.
___
*[pkg/cmd/roachtest/ruby_pg.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjvPpPCpz2QsACObPS:-MZEWy55DEoPwaDx1--F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L171)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we should fail more loudly if this happens -- fail the test rather than warning
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/ruby_pg.go, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjvZ9QEIaB2Bf4jK9s:-MZEX6Ly8_EUX5GDybZe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg.go#L185)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this could also error
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/ruby_pg_blocklist.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjwqoF3pNO_yoyKZmr:-MZEX3l3Cv5KTdubYLRt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg_blocklist.go#L20)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

as we talked about, i'll do an initial pass to get down to root causes at least for some of the tests. the others ones should just be "unknown"
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/ruby_pg.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MZJIa-D1dr0nn70-UMj:-MZJIa-D1dr0nn70-UMk:b-kyt95e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e22bdee5b6f9ca10fddc25f395af7128fea03a2/pkg/cmd/roachtest/ruby_pg.go#L143)):*
> ```Go
> 		)
> 
> 		c.l.Printf("Test Results:\n%s", rawResults)
> ```

do you know if this is all of the logs? or does the test log anything else to separate files (i know java tests do that, but maybe that's just a java thing)
___
*[pkg/cmd/roachtest/ruby_pg_blocklist.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MYjwqoF3pNO_yoyKZmr:-MZJIF3wAow5Xo9X3gVs:bb9r0f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3907a5c6b83fd66e080319125df5c4939f9f56fb/pkg/cmd/roachtest/ruby_pg_blocklist.go#L20)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

we can fill in the reasons later once it starts running nightly and we can look at the logs
___
*[pkg/cmd/roachtest/ruby_pg_blocklist.go, line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MZJINI16q7LZUQ8H9kH:-MZJINI16q7LZUQ8H9kI:b-deqn61) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e22bdee5b6f9ca10fddc25f395af7128fea03a2/pkg/cmd/roachtest/ruby_pg_blocklist.go#L14)):*
> ```Go
> 
> var rubyPGBlocklist = blocklistsForVersion{
> 	{"v20.1", "rubyPGBlockList21_1", rubyPGBlockList20_1, "rubyPGIgnoreList21_1", rubyPGIgnoreList20_1},
> ```

i think we don't really need to test with 20.1; the maintenance period is ending soon
___
*[pkg/cmd/roachtest/ruby_pg_helpers.rb, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MZJHlLC42h04U33HYXI:-MZJHlLC42h04U33HYXJ:bnza48l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e22bdee5b6f9ca10fddc25f395af7128fea03a2/pkg/cmd/roachtest/ruby_pg_helpers.rb#L12)):*
> ```Ruby
> TEST_DIRECTORY = Pathname.new(TEST_DIR_STR)
> 
> module PG::TestingHelpers
> ```

could you add a comment at the top saying what you had to change?

also with this file i'm a little worried that it won't work properly with bazel, since bazel won't pick up `rb` files. i think the `echo`/constant string approach won't run into that problem
___
*[pkg/cmd/roachtest/ruby_pg_helpers.rb, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MZJHd7q1T5C0w-5NqDd:-MZJHd7q1T5C0w-5NqDe:bevpdlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e22bdee5b6f9ca10fddc25f395af7128fea03a2/pkg/cmd/roachtest/ruby_pg_helpers.rb#L376)):*
> ```Ruby
> 	config.filter_run_excluding( :postgresql_10 ) if PG.library_version < 100000
> 	config.filter_run_excluding( :postgresql_12 ) if PG.library_version < 120000
> end
> ```

looks like a weird character here at the end

maybe that's why `echo` had formatting errors?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/ruby_pg_helpers.rb, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MZJHd7q1T5C0w-5NqDd:-MZJKHfSCVUIDOrBdlBf:b-hvqn7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e22bdee5b6f9ca10fddc25f395af7128fea03a2/pkg/cmd/roachtest/ruby_pg_helpers.rb#L376)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

looks like a weird character here at the end

maybe that's why `echo` had formatting errors?
</blockquote></details>

I think this is just a warning that theres no newline at the end, it shows properly on the git side.

I think the echo issue is because there is a " in the ruby file, should work if we properly escape it. Although it seems like bazel accepts this. I prefer to keep this file instead of echoing a string and just transferring the file over ssh if possible though, seems more natural.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/ruby_pg.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MZJIa-D1dr0nn70-UMj:-MZU7wDdEKYBojWc6aZs:blgv5bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e22bdee5b6f9ca10fddc25f395af7128fea03a2/pkg/cmd/roachtest/ruby_pg.go#L143)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you know if this is all of the logs? or does the test log anything else to separate files (i know java tests do that, but maybe that's just a java thing)
</blockquote></details>

I believe it is all of the logs
___
*[pkg/cmd/roachtest/ruby_pg_blocklist.go, line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MZJINI16q7LZUQ8H9kH:-MZU7xneAsw6Vi3-zkVq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e22bdee5b6f9ca10fddc25f395af7128fea03a2/pkg/cmd/roachtest/ruby_pg_blocklist.go#L14)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we don't really need to test with 20.1; the maintenance period is ending soon
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/ruby_pg_helpers.rb, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MZJHlLC42h04U33HYXI:-MZU7zqe7chyxlJ1hEaK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e22bdee5b6f9ca10fddc25f395af7128fea03a2/pkg/cmd/roachtest/ruby_pg_helpers.rb#L12)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you add a comment at the top saying what you had to change?

also with this file i'm a little worried that it won't work properly with bazel, since bazel won't pick up `rb` files. i think the `echo`/constant string approach won't run into that problem
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-:-MZUNCDB08X6qSuB3D9U:b-nzoors)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/ruby_pg_helpers.rb, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63831#-MZJHd7q1T5C0w-5NqDd:-MZUN4bo2B5HMLDqxKS6:b-pi0d8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e22bdee5b6f9ca10fddc25f395af7128fea03a2/pkg/cmd/roachtest/ruby_pg_helpers.rb#L376)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think this is just a warning that theres no newline at the end, it shows properly on the git side.

I think the echo issue is because there is a " in the ruby file, should work if we properly escape it. Although it seems like bazel accepts this. I prefer to keep this file instead of echoing a string and just transferring the file over ssh if possible though, seems more natural.
</blockquote></details>

sounds good if bazel is happy!

**Comment by RichardJCai** [comment]
Thanks!
bors r=rafiss

**Comment by yuzefovich** [comment]
Seems like this needs a rebase:
```
[01:11:08][run] pkg/cmd/roachtest/ruby_pg.go:45:40: not enough arguments in call to fetchCockroachVersion
[01:11:08][run] 	have (context.Context, *cluster, int)
[01:11:08][run] 	want (context.Context, *cluster, int, *SecureDBConnectionParams)
[01:11:08][run] pkg/cmd/roachtest/ruby_pg.go:50:46: not enough arguments in call to alterZoneConfigAndClusterSettings
[01:11:08][run] 	have (context.Context, string, *cluster, int)
[01:11:08][run] 	want (context.Context, string, *cluster, int, *SecureDBConnectionParams)
```

bors r-

**Comment by RichardJCai** [comment]
> Seems like this needs a rebase:
> 
> ```
> [01:11:08][run] pkg/cmd/roachtest/ruby_pg.go:45:40: not enough arguments in call to fetchCockroachVersion
> [01:11:08][run] 	have (context.Context, *cluster, int)
> [01:11:08][run] 	want (context.Context, *cluster, int, *SecureDBConnectionParams)
> [01:11:08][run] pkg/cmd/roachtest/ruby_pg.go:50:46: not enough arguments in call to alterZoneConfigAndClusterSettings
> [01:11:08][run] 	have (context.Context, string, *cluster, int)
> [01:11:08][run] 	want (context.Context, string, *cluster, int, *SecureDBConnectionParams)
> ```
> 
> bors r-

Yep, thanks. Merge skew with my own pr :sweat:
