### PR TITLE
backupccl: re-backup spans that come online during incremental backups

### PR DESCRIPTION
**Pull request by pbardea**
This commit fixes a bug where backup would miss non-transactional writes
(via AddSSTable) during incremental backups. These backups were missed
because AddSSTable can write to a timestamp that is before the previous
incremental backup. So, if a table was written to while OFFLINE (e.g. by
a RESTORE or an IMPORT), during a backup, the following incremental
backup may miss some data.

To resolve this, BACKUP now re-backs up all of the data of OFFLINE
tables on incremental backups that put this table back online. This
comes with the drawback of some incremental backups (when a restore or
import completes) will be much slower since it has to recapture all of
the data.

There is planned future work so that these incrementals only the new
data written by the RESTORE or IMPORT, rather than resorting to backing
up the entire table again. This will be addressed in a later PR.

Implements fix 1 as described in https://github.com/cockroachdb/cockroach/issues/62564, which addresses
the correctness concerns at the expense of incremental backup performance.

Release note (bug fix): Incremental cluster backups may have missed data
written to tables while they were OFFLINE. In practice this can happen
if a RESTORE or IMPORT was running across incremental backups.

### CODE REVIEW

**Review by dt — APPROVED** [review]
great test!

**Comment by pbardea** [comment]
Made a few minor changes to ensure that the reintroduced spans calculation takes into account all revisions of the backup. Another look would be appreciated.

File: pkg/ccl/backupccl/full_cluster_backup_restore_test.go [hunk 1]
```diff
@@ -801,3 +804,96 @@ func TestClusterRevisionHistory(t *testing.T) {
...
+	srcDB.Exec(t, `BACKUP TO $1 WITH revision_history`, clusterBackupLoc)
+
+	var g errgroup.Group
+	g.Go(func() error {
+		_, err := srcDB.DB.ExecContext(ctx, `RESTORE data.bank FROM $1 WITH into_db='restoredb'`, dbBackupLoc)
+		return err
+	})
+
+	// Take an incremental backup after the database restore starts.
+	<-dbRestoreStarted
```
Comment (dt) [inline pkg/ccl/backupccl/full_cluster_backup_restore_test.go:867]: nit: This can make for a hang-y test if the restore stmt breaks that can sometimes be a bit painful to debug if e.g. you break it in a refactor. 

You could move these three steps -- blocking here, the backup, then closing the other ch -- into a second g.Go where you'd have ctx you could select over.

/2¢

**Review by dt — APPROVED** [review]

File: pkg/ccl/backupccl/full_cluster_backup_restore_test.go (hunk 1 above)
Comment (dt) [reply pkg/ccl/backupccl/full_cluster_backup_restore_test.go:867]: (this is not blocking, e.g. if you have a green CI)

Comment (pbardea) [reply pkg/ccl/backupccl/full_cluster_backup_restore_test.go:867]: Ack, CI is green so I'm going to merge to get the backports going. Will circle back to try to at least clean this up on master.

**Comment by pbardea** [comment]
TFTRs
bors r=dt

**Comment by otan** [comment]
🚨 bors patrol 🚨 

```
[01:55:56][Ensure generated code is up-to-date] pkg/ccl/backupccl/targets.go:512:34: too many arguments in call to makeImportSpans
[01:55:56][Ensure generated code is up-to-date] 	have ([]roachpb.Span, []BackupManifest, nil, roachpb.Key, security.SQLUsername, func(covering.Range, hlc.Timestamp, hlc.Timestamp) error)
[01:55:56][Ensure generated code is up-to-date] 	want ([]roachpb.Span, []BackupManifest, map[int]storeByLocalityKV, roachpb.Key, func(covering.Range, hlc.Timestamp, hlc.Timestamp) error)
[01:55:56][Ensure generated code is up-to-date] github.com/cockroachdb/cockroach/pkg/ccl/oidcccl
```

**Comment by pbardea** [comment]
Rebased to address merge skew.
bors r=dt
