### PR TITLE
storage: Fix merge skew from #7380

### LINKED ISSUE #15401: teamcity: failed tests on master: check/TestStyle, check/TestStyle/TestErrCheck, check/TestStyle/TestReturnCheck, check/TestStyle/TestMetacheck, acceptance/TestDockerCLI, acceptance/TestDockerCLI/test_server_restart.tcl
The following tests appear to have failed:

[#235657](https://teamcity.cockroachdb.com/viewLog.html?buildId=235657):

```
--- FAIL: check/TestStyle (26.180s)
null
--- FAIL: check/TestStyle/TestErrCheck (7.940s)
style_test.go:574: err=exit status 2, stderr=/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_test.go:4458:21: too few arguments in call to stopper.Stop
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_test.go:4468:25: cannot use &ts (value of type *github.com/cockroachdb/cockroach/pkg/util/hlc.Timestamp) as github.com/cockroachdb/cockroach/pkg/util/hlc.Timestamp value in assignment
	error: failed to check packages: could not type check: couldn't load packages due to errors: github.com/cockroachdb/cockroach/pkg/storage
--- FAIL: check/TestStyle/TestReturnCheck (10.690s)
style_test.go:598: err=exit status 1, stderr=/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_test.go:4458:21: too few arguments in call to stopper.Stop
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_test.go:4468:25: cannot use &ts (value of type *github.com/cockroachdb/cockroach/pkg/util/hlc.Timestamp) as github.com/cockroachdb/cockroach/pkg/util/hlc.Timestamp value in assignment
--- FAIL: check/TestStyle/TestMetacheck (7.560s)
style_test.go:777: err=exit status 1, stderr=/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_test.go:4458:21: too few arguments in call to stopper.Stop
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_test.go:4468:25: cannot use &ts (value of type *github.com/cockroachdb/cockroach/pkg/util/hlc.Timestamp) as github.com/cockroachdb/cockroach/pkg/util/hlc.Timestamp value in assignment
	couldn't load packages due to errors: github.com/cockroachdb/cockroach/pkg/storage
--- FAIL: acceptance/TestDockerCLI (158.000s)
test_log_scope.go:79: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestDockerCLI500337515
test_log_scope.go:62: use -show-logs to present logs inline
--- FAIL: acceptance/TestDockerCLI/test_server_restart.tcl (36.920s)
cli_test.go:73: non-zero exit code: 1

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #15401

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15405#-:-Kijwhhrx7vQMhg_HcDk:bnfp4nl)*
