### ISSUE TITLE
circleci: failed tests: TestEventLog 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8562]
The following test appears to have failed:

[#21369](https://circleci.com/gh/cockroachdb/cockroach/21369):

```
I160815 21:58:50.949126 acceptance/cluster/docker.go:328  unable to create container volumes: Error response from daemon: Conflict. The name "/volumes" is already in use by container 97cde7c9431d7509103b4389d27c7252295aa188331d5a6578565143af649540. You have to remove (or rename) that container to be able to reuse that name.
W160815 21:58:50.949737 acceptance/cluster/docker.go:358  error indicated existing container volumes, but none found:
error: Error response from daemon: Conflict. The name "/volumes" is already in use by container 97cde7c9431d7509103b4389d27c7252295aa188331d5a6578565143af649540. You have to remove (or rename) that container to be able to reuse that name.
containers: [{ID:bf75d335eeb7353d733349c8edc78a6acd58165a0c08ae6638ecabfbb6274621 Names:[/suspicious_archimedes] Image:cockroachdb/builder:20160808-065131 ImageID:sha256:e95d27b0d1a520f5ca71a6b9531f6053b315f2d75ff8f62871d7be42540f9374 Command:make test 'TESTFLAGS=-v --verbosity=1 --vmodule=monitor=2,tracer=2' Created:1471298049 Ports:[] SizeRw:0 SizeRootFs:0 Labels:map[] State: Status:Exited (0) About a minute ago HostConfig:{NetworkMode:default} NetworkSettings:0xc42002e5a8 Mounts:[]} {ID:0f1b714124758634d1a4a499080878194f3ad2f6e3f57a04701dee464824cd54 Names:[/insane_wescoff] Image:cockroachdb/builder:20160808-065131 ImageID:sha256:e95d27b0d1a520f5ca71a6b9531f6053b315f2d75ff8f62871d7be42540f9374 Command:build/circle-deps.sh docker Created:1471297949 Ports:[] SizeRw:0 SizeRootFs:0 Labels:map[] State: Status:Exited (0) 5 minutes ago HostConfig:{NetworkMode:default} NetworkSettings:0xc42002e5c0 Mounts:[]}]
I160815 21:58:50.949771 acceptance/cluster/localcluster.go:671  stopping
--- FAIL: TestEventLog (14.09s)
panic: ContainerCreate: exceeded 10 tries with a 10s timeout [recovered]
	panic: ContainerCreate: exceeded 10 tries with a 10s timeout [recovered]
	panic: ContainerCreate: exceeded 10 tries with a 10s timeout

goroutine 790 [running]:
panic(0x12fb3e0, 0xc42034baf0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42016aa80)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x12fb3e0, 0xc42034baf0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).stopOnPanic(0xc42014ee00)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:242 +0xa4
panic(0x12fb3e0, 0xc42034baf0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/acceptance/cluster.maybePanic(0x1caae00, 0xc42034baf0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/docker.go:167 +0x5c
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).initCluster(0xc42014ee00)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:376 +0xe8b
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start(0xc42014ee00)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:604 +0xcd
github.com/cockroachdb/cockroach/acceptance.StartCluster(0xc42016aa80, 0xc420105e10, 0x9, 0xc42211c9c0, 0x1, 0x1, 0x12a05f200, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:334 +0x142
github.com/cockroachdb/cockroach/acceptance.runTestOnConfigs.func1(0xc42016aa80, 0xc421cebec8, 0x1551c08)

```
Please assign, take a look and update the issue accordingly.

**Comment by RaduBerinde** [comment]
All retries failed with the same error `Conflict. The name "/volumes" is already in use by container 97cde7c9431d7509103b4389d27c7252295aa188331d5a6578565143af649540. You have to remove (or rename) that container to be able to reuse that name.
W160815 21:58:50.912539 acceptance/cluster/docker.go:358  error indicated existing container volumes, but none found:`

Relevant comment in acceptance/docker.go:
```
356     log.Warningf(ctx, "error indicated existing container %s, "+
357       "but none found:\nerror: %s\ncontainers: %+v",
358       containerName, err, containers)
359     // We likely raced with a previous (late) removal of the container.
360     // Return a timeout so a higher level can retry and hopefully
361     // succeed (or get stuck in an infinite loop, at which point at
362     // least we'll have gathered an additional bit of information).
363     return response, context.DeadlineExceeded
```

**Comment by bdarnell** [comment]
This issue is a weird docker flake which I think we can ignore, but the ones that have been closed as duplicates of this issue are something different:
```
--- FAIL: acceptance/TestEventLog (51.396s)
    testing.go:117: acceptance/event_log_test.go:173, condition failed to evaluate within 45s: Expected only one node restart event, found 0
```

**Comment by tamird** [comment]
Gonna close this in favour of #8706 which has a real failure message.
