### PR TITLE
distsql: split package into distsqlrun and distsqlplan

### PR DESCRIPTION
**Pull request by RaduBerinde**
Separating the code used for the "runtime" of distsql from the code used to do planning. Right now most of the planning code is in `sql` because it uses internals of that package, but it will be migrated to `distsqlplan` in time, as that data becomes available in the IR.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12474)

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
This PR breaks git bisecting, since the individual commits don't compile. Specifically, r4 breaks with 
`pkg/sql/distsql_physical_planner.go:67: undefined: distsqlrun.SpanResolver`
r3 builds fine.
r2 breaks with
`pkg/sql/distsql_aggregator_visitors.go:26:2: cannot find package "github.com/cockroachdb/cockroach/pkg/sql/distsql" in any of:
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cockroach/pkg/sql/distsql (vendor tree)
	/usr/local/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql (from $GOROOT)
	/Users/arjun/goworkspace/src/github.com/cockroachdb/cockroach/pkg/sql/distsql (from $GOPATH)
make: *** [install] Error 1`, and r1 breaks with something similar as well.

---

Reviewed 12 of 106 files at r1.
Review status: 0 of 59 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12474#-:-KZNBj0JhTWNAtaMZsi7:bdlg0qv)*

**Comment by RaduBerinde** [comment]
I can squash them after review but why would git bisect go through the commits on this branch? There would be a single "merge" commit in the master branch.

---

Review status: 0 of 59 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12474#-:-KZNDPp4Ccizub_-MWKJ:b-uik8ld)*

**Comment by bdarnell** [comment]
> I can squash them after review but why would git bisect go through the commits on this branch? There would be a single "merge" commit in the master branch.

In git (unlike mercurial), commits aren't associated with a branch, they're just part of the DAG. `git bisect` avoids making assumptions about workflow so it looks at both sides of a merge commit equally. A mode for `git bisect` that only looks at the first parents of merge commits (corresponding to the history of the `master` branch for the standard github PR workflow) would seem to make sense but doesn't exist. 

So merging branches with commits that don't compile can cause problems for `git bisect` in the future (requiring the use of `git bisect skip`). On the other hand, separate commits can be useful for looking at logs and diffs in the future, just as they are during the initial review. I don't have a strong preference here but I'd personally merge with separate commits even if it inconveniences future bisections.

**Comment by RaduBerinde** [comment]
Ah, I see. This is right, I was confused by some questions on stackoverflow. I squashed the first three commits (since they're all about renaming the package) and left the last one separate.

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 59 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12474#-:-KZRzQBbgKUszMaR6JZV:bnfp4nl)*
